const { PrismaClient } = require('@prisma/client');
const bcrypt = require('bcryptjs');

const prisma = new PrismaClient();

async function main() {
  console.log('Seeding initial data for SIPIKEM SULUT (Dinas Perindustrian dan Perdagangan Provinsi Sulawesi Utara)...');

  // 1. Create / Update Superadmin Account
  const superadminPassword = await bcrypt.hash('superadmin123', 10);
  const superadmin = await prisma.user.upsert({
    where: { username: 'superadmin' },
    update: {
      password: superadminPassword,
      name: 'Super Administrator SIPIKEM',
      email: 'superadmin@sulutprov.go.id',
      role: 'SUPERADMIN',
    },
    create: {
      username: 'superadmin',
      name: 'Super Administrator SIPIKEM',
      email: 'superadmin@sulutprov.go.id',
      password: superadminPassword,
      role: 'SUPERADMIN',
    },
  });
  console.log('Superadmin user ready:', superadmin.username, `(${superadmin.role})`);

  // 1b. Update existing 'admin' account to SUPERADMIN
  const adminPassword = await bcrypt.hash('admin123', 10);
  const admin = await prisma.user.upsert({
    where: { username: 'admin' },
    update: {
      password: adminPassword,
      name: 'Admin Disperindag Sulut',
      email: 'admin@sulutprov.go.id',
      role: 'SUPERADMIN',
    },
    create: {
      username: 'admin',
      name: 'Admin Disperindag Sulut',
      email: 'admin@sulutprov.go.id',
      password: adminPassword,
      role: 'SUPERADMIN',
    },
  });
  console.log('Admin user ready:', admin.username, `(${admin.role})`);

  // 1c. Create dedicated Verifikator
  const verifikatorPassword = await bcrypt.hash('admin123', 10);
  const verifikator = await prisma.user.upsert({
    where: { username: 'verifikator' },
    update: {
      password: verifikatorPassword,
      name: 'Petugas Pembina IKM Sulut',
      email: 'verifikator@sulutprov.go.id',
      role: 'ADMIN',
    },
    create: {
      username: 'verifikator',
      name: 'Petugas Pembina IKM Sulut',
      email: 'verifikator@sulutprov.go.id',
      password: verifikatorPassword,
      role: 'ADMIN',
    },
  });
  console.log('Verifikator user ready:', verifikator.username, `(${verifikator.role})`);

  // 2. Clear existing merchants to populate 25 Authentic Pilot Project IKM
  await prisma.merchantRegistration.deleteMany({});
  console.log('Populating 25 Pilot Project IKM Sulut matching data ikm.jpeg & DATA IKM.pdf...');

  const pilotIKM = [
    {
      registrationNo: 'IKM-SULUT-2026-001',
      nik: '7102011504850001',
      ownerName: 'Vicky Paat',
      phone: '081244112233',
      email: 'kopitondano@gmail.com',
      businessName: 'Kopi Tondano',
      yearFounded: 2018,
      regency: 'Kab. Minahasa',
      district: 'Tondano Barat',
      village: 'Rerewokan',
      address: 'Jl. Sam Ratulangi No. 45, Tondano',
      postalCode: '95614',
      latitude: 1.3065,
      longitude: 124.9125,
      category: 'Makanan & Minuman',
      scale: 'Kecil',
      employeeCount: 6,
      mainProduct: 'Kopi Bubuk',
      productType: 'Kopi Arabika & Robusta Roasting',
      rawMaterial: 'Biji Kopi Petani Minahasa',
      productionCapacity: '1.200 kemasan / bulan',
      productPrice: 45000,
      productAdvantage: 'Aroma khas dataran tinggi Tondano, pengeringan natural',
      nib: '9120003410291',
      businessLicense: 'Ada',
      npwp: '84.921.345.1-821.000',
      halalCert: 'ID7111000045231',
      bpomPirt: 'P-IRT 2107102010452-26',
      haki: 'Kopi Tondano Asli',
      productionEquipment: 'Mesin Roasting Kapasitas 5kg, Sealer Otomatis',
      monthlyRevenue: 35000000,
      marketChannels: 'Online & Offline',
      socialMedia: '@kopitondano.official (Instagram, Tokopedia)',
      fundingSource: 'Modal Mandiri & KUR',
      bankAccess: 'KUR BRI Rp 50.000.000',
      partnerships: 'BUMN Rumah BUMN Manado, Kafe Lokal',
      needs: 'Peningkatan kapasitas kemasan gusset valve, akses pasar ritel modern',
      ikmScore: 'Berkembang',
      mentoringStatus: 'Pendampingan',
      status: 'APPROVED',
      adminNotes: 'Data lengkap, legalitas halal & P-IRT aktif. Siap didorong akses pasar ritel modern.',
      verifiedAt: new Date(),
      verifiedBy: 'Petugas Pembina IKM Sulut',
      ktpImage: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=600&auto=format&fit=crop&q=60',
      businessImage: 'https://images.unsplash.com/photo-1587734195503-904fca47e0e9?w=600&auto=format&fit=crop&q=60',
    },
    {
      registrationNo: 'IKM-SULUT-2026-002',
      nik: '7171032207820003',
      ownerName: 'Stenly Manopo',
      phone: '081356889900',
      email: 'nyiursejahtera@yahoo.com',
      businessName: 'Nyiur Sejahtera',
      yearFounded: 2020,
      regency: 'Kota Manado',
      district: 'Mapanget',
      village: 'Paniki Bawah',
      address: 'Jl. AA Maramis Km 9, Mapanget',
      postalCode: '95256',
      latitude: 1.5200,
      longitude: 124.8900,
      category: 'Olahan Kelapa',
      scale: 'Kecil',
      employeeCount: 8,
      mainProduct: 'Minyak Kelapa',
      productType: 'Minyak Kelapa Murni & Goreng Tradisional',
      rawMaterial: 'Kelapa Segar Petani Sulut',
      productionCapacity: '3.000 liter / bulan',
      productPrice: 32000,
      productAdvantage: 'Bebas kolesterol, aroma harum tanpa bahan pengawet',
      nib: '9120005521098',
      businessLicense: 'Ada',
      npwp: '75.312.441.2-821.000',
      halalCert: 'Dalam Proses',
      bpomPirt: 'P-IRT 2057171010321-25',
      haki: 'Nyiur Sejahtera',
      productionEquipment: 'Mesin Press Kelapa Hidrolik, Filter Centrifuge',
      monthlyRevenue: 65000000,
      marketChannels: 'Offline',
      socialMedia: 'Facebook: Minyak Kelapa Nyiur',
      fundingSource: 'Modal Sendiri',
      bankAccess: 'Belum Ada',
      partnerships: 'Toko Swalayan Lokal Manado',
      needs: 'Digital marketing, sertifikasi BPOM untuk ekspor',
      ikmScore: 'Maju',
      mentoringStatus: 'Pendampingan',
      status: 'APPROVED',
      adminNotes: 'Kapasitas produksi sangat stabil. Rekomendasi pendampingan pemasaran online.',
      verifiedAt: new Date(),
      verifiedBy: 'Drs. Hendrik R. Tendean',
      ktpImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&auto=format&fit=crop&q=60',
      businessImage: 'https://images.unsplash.com/photo-1620706857370-e1b9770e8bb1?w=600&auto=format&fit=crop&q=60',
    },
    {
      registrationNo: 'IKM-SULUT-2026-003',
      nik: '7172014409890002',
      ownerName: 'Meike Tumbelaka',
      phone: '081143223344',
      email: 'ratucakalang@gmail.com',
      businessName: 'Ratu Cakalang',
      yearFounded: 2019,
      regency: 'Kota Bitung',
      district: 'Aertembaga',
      village: 'Aertembaga Satu',
      address: 'Jl. Pelabuhan Perikanan No. 12, Bitung',
      postalCode: '95521',
      latitude: 1.4420,
      longitude: 125.1950,
      category: 'Perikanan',
      scale: 'Kecil',
      employeeCount: 5,
      mainProduct: 'Ikan Cakalang Asap',
      productType: 'Cakalang Fufu & Sambal Roa Cakalang',
      rawMaterial: 'Ikan Cakalang Segar Pelabuhan Bitung',
      productionCapacity: '800 ekor / bulan',
      productPrice: 65000,
      productAdvantage: 'Pengasapan tempurung kelapa alami, daging padat kemerahan',
      nib: '9120008819201',
      businessLicense: 'Ada',
      npwp: '91.821.092.3-822.000',
      halalCert: 'Dalam Proses',
      bpomPirt: 'P-IRT 2027172010112-26',
      haki: 'Ratu Cakalang Bitung',
      productionEquipment: 'Rumah Asap Higienis, Vacuum Sealer Industri',
      monthlyRevenue: 42000000,
      marketChannels: 'Online & Offline',
      socialMedia: '@ratucakalang.bitung (Shopee, IG)',
      fundingSource: 'Modal Mandiri',
      bankAccess: 'Kredit Mikro Bank SulutGo',
      partnerships: 'Oleh-oleh Manado, Restoran Seafood',
      needs: 'Teknologi pengemasan retort pouch tahan 1 tahun tanpa pendingin',
      ikmScore: 'Berkembang',
      mentoringStatus: 'Analisis Kebutuhan',
      status: 'APPROVED',
      adminNotes: 'Produk unggulan perikanan Bitung. Masuk program fasilitasi kemasan retort pouch.',
      verifiedAt: new Date(),
      verifiedBy: 'Petugas Pembina IKM Sulut',
      ktpImage: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=600&auto=format&fit=crop&q=60',
      businessImage: 'https://images.unsplash.com/photo-1534939561126-855b8675edd7?w=600&auto=format&fit=crop&q=60',
    },
    {
      registrationNo: 'IKM-SULUT-2026-004',
      nik: '7106021102910005',
      ownerName: 'Yantje Rondonuwu',
      phone: '085240112299',
      email: 'kerajinanwineru@gmail.com',
      businessName: 'Kerajinan Kayu Wineru',
      yearFounded: 2021,
      regency: 'Kab. Minahasa Utara',
      district: 'Likupang Timur',
      village: 'Wineru',
      address: 'Desa Wineru Jaga II, Kawasan KEK Likupang',
      postalCode: '95377',
      latitude: 1.6850,
      longitude: 125.0520,
      category: 'Kerajinan',
      scale: 'Mikro',
      employeeCount: 4,
      mainProduct: 'Kerajinan Kayu',
      productType: 'Peralatan Makan Kayu & Souvenir KEK Likupang',
      rawMaterial: 'Limbah Kayu Kelapa & Mahoni Legal',
      productionCapacity: '400 pcs / bulan',
      productPrice: 35000,
      productAdvantage: 'Finishing food-grade natural beeswax, ramah lingkungan',
      nib: '9120004128912',
      businessLicense: 'Ada',
      npwp: null,
      halalCert: null,
      bpomPirt: null,
      haki: null,
      productionEquipment: 'Mesin Bubut Kayu Manual, Sanding Tool',
      monthlyRevenue: 12000000,
      marketChannels: 'Offline',
      socialMedia: null,
      fundingSource: 'Modal Mandiri',
      bankAccess: 'Belum Ada',
      partnerships: 'Resort Likupang',
      needs: 'Fasilitasi HAKI merek, pelatihan katalog digital dan mesin bubut CNC',
      ikmScore: 'Pemula',
      mentoringStatus: 'Pendataan',
      status: 'PENDING',
      adminNotes: 'Potensial untuk souvenir DPSP Likupang. Perlu pendampingan NIB dan branding.',
      verifiedAt: null,
      verifiedBy: null,
      ktpImage: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=600&auto=format&fit=crop&q=60',
      businessImage: 'https://images.unsplash.com/photo-1538688525198-9b88f6f53126?w=600&auto=format&fit=crop&q=60',
    },
    {
      registrationNo: 'IKM-SULUT-2026-005',
      nik: '7173016203870001',
      ownerName: 'Priscilia Supit',
      phone: '081288990011',
      email: 'batikminahasa@tomohon.go.id',
      businessName: 'Batik Minahasa',
      yearFounded: 2017,
      regency: 'Kota Tomohon',
      district: 'Tomohon Tengah',
      village: 'Kolongan',
      address: 'Jl. Lingkar Timur No. 18, Tomohon',
      postalCode: '95442',
      latitude: 1.3280,
      longitude: 124.8410,
      category: 'Fashion',
      scale: 'Kecil',
      employeeCount: 7,
      mainProduct: 'Kain Batik',
      productType: 'Batik Tulis & Cap Motif Tarik Saloi & Pinabetengan',
      rawMaterial: 'Kain Katun Primissima, Sutra ATBM',
      productionCapacity: '150 meter / bulan',
      productPrice: 275000,
      productAdvantage: 'Motif budaya otentik Minahasa, pewarna alam daun mangga',
      nib: '9120001192834',
      businessLicense: 'Ada',
      npwp: '73.291.849.2-821.000',
      halalCert: null,
      bpomPirt: null,
      haki: 'Sertifikat Hak Cipta Motif Saloi',
      productionEquipment: 'Canting Listrik, Meja Cap Tembaga, Gawangan Kayu',
      monthlyRevenue: 38000000,
      marketChannels: 'Online',
      socialMedia: '@batikminahasa_tomohon (Instagram, Website)',
      fundingSource: 'Modal Mandiri',
      bankAccess: 'KUR BNI Rp 100.000.000',
      partnerships: 'Dekranasda Prov Sulut, Hotel Bintang Manado',
      needs: 'Business matching pameran fashion nasional & ekspor',
      ikmScore: 'Berkembang',
      mentoringStatus: 'Pendampingan',
      status: 'APPROVED',
      adminNotes: 'Kualitas karya sangat halus, terdaftar HAKI. Siap diikutsertakan di pameran nasional.',
      verifiedAt: new Date(),
      verifiedBy: 'Drs. Hendrik R. Tendean',
      ktpImage: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=600&auto=format&fit=crop&q=60',
      businessImage: 'https://images.unsplash.com/photo-1607344645866-009c320c5ab8?w=600&auto=format&fit=crop&q=60',
    },
    {
      registrationNo: 'IKM-SULUT-2026-006',
      nik: '7102041908770004',
      ownerName: 'Franky Rompas',
      phone: '081340998811',
      email: 'cengkehsejati@gmail.com',
      businessName: 'Cengkeh Sejati',
      yearFounded: 2015,
      regency: 'Kab. Minahasa',
      district: 'Kawangkoan',
      village: 'Sendangan',
      address: 'Jl. Raya Kawangkoan - Sonder Km 2',
      postalCode: '95692',
      latitude: 1.1980,
      longitude: 124.7890,
      category: 'Pertanian & Perkebunan',
      scale: 'Menengah',
      employeeCount: 14,
      mainProduct: 'Cengkeh Kering',
      productType: 'Cengkeh Kering Super Zanzibar & Minyak Atsiri Cengkeh',
      rawMaterial: 'Bunga Cengkeh Perkebunan Minahasa',
      productionCapacity: '4 ton / musim panen',
      productPrice: 125000,
      productAdvantage: 'Kadar air < 12%, minyak atsiri tinggi, sortasi ketat',
      nib: '9120007719283',
      businessLicense: 'Ada',
      npwp: '81.992.019.4-821.000',
      halalCert: null,
      bpomPirt: null,
      haki: 'Cengkeh Sejati Minahasa',
      productionEquipment: 'Solar Dryer Dome, Mesin Distilasi Minyak Atsiri Stainless',
      monthlyRevenue: 120000000,
      marketChannels: 'Offline',
      socialMedia: null,
      fundingSource: 'Modal Mandiri & Pinjaman Komersial',
      bankAccess: 'Kredit Investasi Bank Mandiri',
      partnerships: 'Eksportir Rempah Surabaya, Industri Rokok Kretek',
      needs: 'Akses langsung buyer luar negeri (ekspor langsung dari Pelabuhan Bitung)',
      ikmScore: 'Maju',
      mentoringStatus: 'Pendampingan',
      status: 'APPROVED',
      adminNotes: 'Komoditas andalan Sulut. Direkomendasikan untuk Business Matching Trade Expo.',
      verifiedAt: new Date(),
      verifiedBy: 'Drs. Hendrik R. Tendean',
      ktpImage: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=600&auto=format&fit=crop&q=60',
      businessImage: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&auto=format&fit=crop&q=60',
    },
    {
      registrationNo: 'IKM-SULUT-2026-007',
      nik: '7171016508920004',
      ownerName: 'Jein Kalalo',
      phone: '081244778899',
      email: 'anekarica.manado@gmail.com',
      businessName: 'Aneka Rica',
      yearFounded: 2020,
      regency: 'Kota Manado',
      district: 'Wenang',
      village: 'Bumi Beringin',
      address: 'Jl. 17 Agustus Lorong Melati No. 5, Manado',
      postalCode: '95113',
      latitude: 1.4720,
      longitude: 124.8390,
      category: 'Makanan & Minuman',
      scale: 'Kecil',
      employeeCount: 5,
      mainProduct: 'Sambal Rica',
      productType: 'Sambal Rica Roa, Sambal Cumi Asap, Sambal Dabu-dabu Botol',
      rawMaterial: 'Cabe Rawit Gorontalo, Ikan Roa Tagulandang, Bawang Merah Minahasa',
      productionCapacity: '1.500 jar / bulan',
      productPrice: 38000,
      productAdvantage: 'Pedas otentik Manado, steril pasteurisasi tahan 6 bulan',
      nib: '9120009928172',
      businessLicense: 'Ada',
      npwp: '89.112.455.1-821.000',
      halalCert: 'Dalam Proses',
      bpomPirt: 'P-IRT 2117171010891-26',
      haki: 'Aneka Rica Manado',
      productionEquipment: 'Mesin Chopper Stainless, Mesin Pasteurisasi Suhu Terkontrol',
      monthlyRevenue: 34000000,
      marketChannels: 'Online & Offline',
      socialMedia: '@anekarica.mdo (TikTok Shop, Shopee)',
      fundingSource: 'Modal Mandiri',
      bankAccess: 'KUR BRI Rp 25.000.000',
      partnerships: 'Supermarket FreshMart Manado',
      needs: 'Fasilitasi Sertifikasi Halal resmi BPJPH dan optimasi iklan live streaming',
      ikmScore: 'Berkembang',
      mentoringStatus: 'Pendampingan',
      status: 'APPROVED',
      adminNotes: 'Penjualan online sangat bagus. Menunggu jadwal audit halal BPJPH.',
      verifiedAt: new Date(),
      verifiedBy: 'Petugas Pembina IKM Sulut',
      ktpImage: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=600&auto=format&fit=crop&q=60',
      businessImage: 'https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?w=600&auto=format&fit=crop&q=60',
    },
    {
      registrationNo: 'IKM-SULUT-2026-008',
      nik: '7109012301840002',
      ownerName: 'Hermanto Salindeho',
      phone: '082199001122',
      email: 'kelapasitaro@vco.co.id',
      businessName: 'Kelapa Sitaro',
      yearFounded: 2019,
      regency: 'Kab. Kepulauan Sitaro',
      district: 'Siau Timur',
      village: 'Akarbagu',
      address: 'Kawasan Pesisir Pelabuhan Ulu Siau',
      postalCode: '95861',
      latitude: 2.7410,
      longitude: 125.3950,
      category: 'Olahan Kelapa',
      scale: 'Kecil',
      employeeCount: 6,
      mainProduct: 'Virgin Coconut Oil',
      productType: 'VCO Cold-Pressed Ekstra Murni & Minyak Urut Herbal',
      rawMaterial: 'Kelapa Segar Pulau Siau',
      productionCapacity: '1.000 botol / bulan',
      productPrice: 60000,
      productAdvantage: 'Metode fermentasi dingin tanpa pemanasan, kadar asam laurat tinggi',
      nib: '9120003381920',
      businessLicense: 'Ada',
      npwp: '78.912.001.4-823.000',
      halalCert: 'ID7112000089123',
      bpomPirt: 'P-IRT 2077109010112-25',
      haki: 'Sitaro Virgin Oil',
      productionEquipment: 'Mesin Parut Kelapa, Cold Press Centrifuge Stainless 304',
      monthlyRevenue: 48000000,
      marketChannels: 'Online',
      socialMedia: 'Website: www.kelapasitaro.com, IG: @vco_sitaro',
      fundingSource: 'Modal Mandiri & Hibah Kemenperin',
      bankAccess: 'Bank SulutGo',
      partnerships: 'Distributor Skincare Organik Bali & Jakarta',
      needs: 'Uji klinis laboratorium lanjutan & sertifikasi BPOM MD',
      ikmScore: 'Maju',
      mentoringStatus: 'Pendampingan',
      status: 'APPROVED',
      adminNotes: 'Produk olahan kelapa kepulauan bermutu prima, telah mengantongi sertifikat halal.',
      verifiedAt: new Date(),
      verifiedBy: 'Drs. Hendrik R. Tendean',
      ktpImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&auto=format&fit=crop&q=60',
      businessImage: 'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=600&auto=format&fit=crop&q=60',
    },
    {
      registrationNo: 'IKM-SULUT-2026-009',
      nik: '7104021805880003',
      ownerName: 'Alberth Paparang',
      phone: '085342119900',
      email: 'palatalaud@gmail.com',
      businessName: 'Olahan Pala',
      yearFounded: 2022,
      regency: 'Kab. Kepulauan Talaud',
      district: 'Melonguane',
      village: 'Kiama',
      address: 'Desa Kiama, Kecamatan Melonguane',
      postalCode: '95885',
      latitude: 4.0020,
      longitude: 126.6850,
      category: 'Makanan & Minuman',
      scale: 'Mikro',
      employeeCount: 3,
      mainProduct: 'Pala Bubuk',
      productType: 'Bubuk Biji Pala Murni & Daging Pala Kering',
      rawMaterial: 'Biji Pala & Fuli Pulau Karakelang Talaud',
      productionCapacity: '350 kg / bulan',
      productPrice: 75000,
      productAdvantage: 'Biji pala aromatik daerah perbatasan NKRI, 100% murni tanpa campuran',
      nib: '9120004491029',
      businessLicense: 'Ada',
      npwp: null,
      halalCert: null,
      bpomPirt: null,
      haki: null,
      productionEquipment: 'Mesin Penepung Granulator Sederhana',
      monthlyRevenue: 14000000,
      marketChannels: 'Offline',
      socialMedia: null,
      fundingSource: 'Modal Mandiri',
      bankAccess: 'Belum Ada',
      partnerships: 'Pengepul Rempah Melonguane',
      needs: 'Fasilitasi P-IRT, perbaikan kemasan kedap udara, dan biaya logistik antar-pulau',
      ikmScore: 'Pemula',
      mentoringStatus: 'Analisis Kebutuhan',
      status: 'APPROVED',
      adminNotes: 'Potensi rempah perbatasan sangat tinggi. Memerlukan bantuan pendampingan izin edar.',
      verifiedAt: new Date(),
      verifiedBy: 'Petugas Pembina IKM Sulut',
      ktpImage: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=600&auto=format&fit=crop&q=60',
      businessImage: 'https://images.unsplash.com/photo-1599940824399-b87987ceb72a?w=600&auto=format&fit=crop&q=60',
    },
    {
      registrationNo: 'IKM-SULUT-2026-010',
      nik: '7103015406850001',
      ownerName: 'Siti Dalope',
      phone: '081340112288',
      email: 'keripik.sangihe@yahoo.com',
      businessName: 'Keripik Pisang Sangihe',
      yearFounded: 2020,
      regency: 'Kab. Kepulauan Sangihe',
      district: 'Tahuna',
      village: 'Soataloara I',
      address: 'Jl. Tatehe No. 24, Tahuna',
      postalCode: '95812',
      latitude: 3.6120,
      longitude: 125.4850,
      category: 'Makanan & Minuman',
      scale: 'Mikro',
      employeeCount: 4,
      mainProduct: 'Keripik Pisang',
      productType: 'Keripik Pisang Goroho Gurih & Manis Caramel',
      rawMaterial: 'Pisang Goroho Khas Kepulauan Sangihe',
      productionCapacity: '600 bungkus / bulan',
      productPrice: 20000,
      productAdvantage: 'Renyah resep tradisional Sangihe, indeks glikemik rendah pisang goroho',
      nib: '9120001829102',
      businessLicense: 'Ada',
      npwp: null,
      halalCert: 'Dalam Proses',
      bpomPirt: 'P-IRT 2147103010198-25',
      haki: 'Goroho Sangihe Snack',
      productionEquipment: 'Mesin Spinner Minyak Peniris, Alat Slicer Pisang',
      monthlyRevenue: 15000000,
      marketChannels: 'Online',
      socialMedia: '@keripikgoroho_sangihe (Facebook Marketplace)',
      fundingSource: 'Modal Mandiri',
      bankAccess: 'KUR BRI Rp 20.000.000',
      partnerships: 'Koperasi Bahari Tahuna',
      needs: 'Desain kemasan standing pouch metalized foil & sertifikasi halal',
      ikmScore: 'Berkembang',
      mentoringStatus: 'Pendampingan',
      status: 'APPROVED',
      adminNotes: 'Camilan favorit wisatawan. Masuk ke program Klinik Kemasan Disperindag Sulut.',
      verifiedAt: new Date(),
      verifiedBy: 'Petugas Pembina IKM Sulut',
      ktpImage: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=600&auto=format&fit=crop&q=60',
      businessImage: 'https://images.unsplash.com/photo-1621996346565-e3d5d628169a?w=600&auto=format&fit=crop&q=60',
    },
    {
      registrationNo: 'IKM-SULUT-2026-011',
      nik: '7105021903820005',
      ownerName: 'Hendro Liwe',
      phone: '081245009988',
      email: 'aren.ranoyapo@gmail.com',
      businessName: 'Gula Aren Ranoyapo',
      yearFounded: 2016,
      regency: 'Kab. Minahasa Selatan',
      district: 'Ranoyapo',
      village: 'Poopo',
      address: 'Desa Poopo Jaga III, Ranoyapo',
      postalCode: '95353',
      latitude: 1.0500,
      longitude: 124.6200,
      category: 'Makanan & Minuman',
      scale: 'Kecil',
      employeeCount: 8,
      mainProduct: 'Gula Semut Aren',
      productType: 'Gula Semut Aren Organik & Gula Cetak Tradisional',
      rawMaterial: 'Nira Aren Hutan Pegunungan Minsel',
      productionCapacity: '2.500 kg / bulan',
      productPrice: 35000,
      productAdvantage: 'Indeks glikemik rendah, organik tanpa campuran bahan kimia',
      nib: '9120005510294',
      businessLicense: 'Ada',
      npwp: '82.912.451.2-821.000',
      halalCert: 'ID7111000109281',
      bpomPirt: 'P-IRT 2097105010092-26',
      haki: 'Ranoyapo Aren',
      productionEquipment: 'Wajan Stainless Gula Semut, Mesin Pengayak Mesh 18',
      monthlyRevenue: 52000000,
      marketChannels: 'Online & Offline',
      socialMedia: '@gulaaren.ranoyapo',
      fundingSource: 'Modal Mandiri',
      bankAccess: 'Kredit BNI Wirausaha',
      partnerships: 'Coffee Shop Jaringan Nasional',
      needs: 'Sertifikasi Organik Internasional untuk peluang ekspor',
      ikmScore: 'Maju',
      mentoringStatus: 'Pendampingan',
      status: 'APPROVED',
      adminNotes: 'Komoditas andalan gula aren Minsel. Sudah siap naik kelas ke pasar global.',
      verifiedAt: new Date(),
      verifiedBy: 'Drs. Hendrik R. Tendean',
      ktpImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&auto=format&fit=crop&q=60',
      businessImage: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=600&auto=format&fit=crop&q=60',
    },
    {
      registrationNo: 'IKM-SULUT-2026-012',
      nik: '7101031407870002',
      ownerName: 'Dedi Mokoginta',
      phone: '085298112233',
      email: 'kopimodayag@gmail.com',
      businessName: 'Kopi Robusta Modayag',
      yearFounded: 2021,
      regency: 'Kab. Bolaang Mongondow',
      district: 'Modayag',
      village: 'Modayag Barat',
      address: 'Jl. Trans AKD Km 15, Modayag',
      postalCode: '95781',
      latitude: 0.7500,
      longitude: 124.4100,
      category: 'Makanan & Minuman',
      scale: 'Mikro',
      employeeCount: 4,
      mainProduct: 'Kopi Biji & Bubuk',
      productType: 'Kopi Robusta Pegunungan Bolmong',
      rawMaterial: 'Kopi Petik Merah Kebun Rakyat',
      productionCapacity: '500 kg / bulan',
      productPrice: 40000,
      productAdvantage: 'Bodi tebal dengan citarasa cokelat karamel alami',
      nib: '9120008891023',
      businessLicense: 'Ada',
      npwp: null,
      halalCert: null,
      bpomPirt: 'P-IRT 2107101010341-26',
      haki: null,
      productionEquipment: 'Mesin Pulper Kopi, Roaster Kapasitas 2kg',
      monthlyRevenue: 16000000,
      marketChannels: 'Offline',
      socialMedia: null,
      fundingSource: 'Modal Mandiri',
      bankAccess: 'Belum Ada',
      partnerships: 'Kedai Kopi Kotamobagu',
      needs: 'Peningkatan kapasitas mesin roasting dan legalitas halal',
      ikmScore: 'Berkembang',
      mentoringStatus: 'Pendataan',
      status: 'APPROVED',
      adminNotes: 'Potensi kopi Bolmong sangat besar. Masuk daftar pendampingan legalitas & mutu.',
      verifiedAt: new Date(),
      verifiedBy: 'Petugas Pembina IKM Sulut',
      ktpImage: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=600&auto=format&fit=crop&q=60',
      businessImage: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=600&auto=format&fit=crop&q=60',
    },
    {
      registrationNo: 'IKM-SULUT-2026-013',
      nik: '7172021901800001',
      ownerName: 'Erwin Tangkudung',
      phone: '081143556677',
      email: 'abontunabitung@gmail.com',
      businessName: 'Abon Tuna Bitung Bahari',
      yearFounded: 2014,
      regency: 'Kota Bitung',
      district: 'Madidir',
      village: 'Madidir Weru',
      address: 'Jl. Sam Ratulangi No. 88, Madidir, Bitung',
      postalCode: '95514',
      latitude: 1.4550,
      longitude: 125.1780,
      category: 'Perikanan',
      scale: 'Menengah',
      employeeCount: 16,
      mainProduct: 'Abon Ikan Tuna',
      productType: 'Abon Tuna Original & Pedas Daun Jeruk',
      rawMaterial: 'Ikan Tuna Sirip Kuning (Yellowfin) Bitung',
      productionCapacity: '2.500 jar / bulan',
      productPrice: 55000,
      productAdvantage: 'Tinggi protein, non-MSG, sertifikasi HACCP & Halal',
      nib: '9120001188291',
      businessLicense: 'Ada',
      npwp: '03.291.841.2-822.000',
      halalCert: 'ID7111000001298',
      bpomPirt: 'BPOM RI MD 243231001092',
      haki: 'Bitung Bahari Abon',
      productionEquipment: 'Mesin Suwir Daging Ikan, Wajan Otomatis Pengering Abon',
      monthlyRevenue: 95000000,
      marketChannels: 'Online & Offline',
      socialMedia: 'Website: www.bitungbahari.id, IG: @abon_bitungbahari',
      fundingSource: 'Modal Mandiri',
      bankAccess: 'Kredit Korporasi Bank SulutGo',
      partnerships: 'Retail Modern Nasional (Indomaret, Alfamidi)',
      needs: 'Penjajakan ekspor ke pasar Filipina dan Jepang (Business Matching)',
      ikmScore: 'Unggulan',
      mentoringStatus: 'Akses Pasar',
      status: 'APPROVED',
      adminNotes: 'IKM Percontohan Unggulan Sulut. Siap mengikuti Business Matching Internasional.',
      verifiedAt: new Date(),
      verifiedBy: 'Drs. Hendrik R. Tendean',
      ktpImage: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=600&auto=format&fit=crop&q=60',
      businessImage: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=600&auto=format&fit=crop&q=60',
    },
    {
      registrationNo: 'IKM-SULUT-2026-014',
      nik: '7102066504780003',
      ownerName: 'Ibu Norma Lontoh',
      phone: '081340889922',
      email: 'tenunbentenan@minahasa.go.id',
      businessName: 'Tenun Bentenan Pinabetengan',
      yearFounded: 2012,
      regency: 'Kab. Minahasa',
      district: 'Tompaso',
      village: 'Pinabetengan',
      address: 'Sentra Budaya Pinabetengan, Tompaso',
      postalCode: '95693',
      latitude: 1.1820,
      longitude: 124.8100,
      category: 'Fashion',
      scale: 'Kecil',
      employeeCount: 10,
      mainProduct: 'Kain Tenun Tradisional',
      productType: 'Tenun Songket Motif Pinantikan, Kaiwu Patola',
      rawMaterial: 'Benang Sutra & Katun Alam',
      productionCapacity: '60 lembar kain / bulan',
      productPrice: 650000,
      productAdvantage: 'Karya seni budaya legendaris Minahasa dengan HAKI resmi',
      nib: '9120002291024',
      businessLicense: 'Ada',
      npwp: '79.221.092.1-821.000',
      halalCert: null,
      bpomPirt: null,
      haki: 'Kain Tenun Bentenan Minahasa',
      productionEquipment: '10 Alat Tenun Bukan Mesin (ATBM) Tradisional',
      monthlyRevenue: 45000000,
      marketChannels: 'Online & Offline',
      socialMedia: '@tenunbentenan_official',
      fundingSource: 'Modal Mandiri',
      bankAccess: 'Bank Indonesia Mitra Binaan',
      partnerships: 'Kementerian Perindustrian, Desainer Nasional',
      needs: 'Regenerasi penenun muda dan akses pasar fashion ekspor',
      ikmScore: 'Unggulan',
      mentoringStatus: 'Akses Pasar',
      status: 'APPROVED',
      adminNotes: 'Kekayaan budaya warisan luhur Sulut. Telah diusulkan dalam katalog fashion dunia.',
      verifiedAt: new Date(),
      verifiedBy: 'Drs. Hendrik R. Tendean',
      ktpImage: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=600&auto=format&fit=crop&q=60',
      businessImage: 'https://images.unsplash.com/photo-1528459801416-a9e53bbf4e17?w=600&auto=format&fit=crop&q=60',
    },
    {
      registrationNo: 'IKM-SULUT-2026-015',
      nik: '7105035208890001',
      ownerName: 'Meyti Sumual',
      phone: '082291002233',
      email: 'dodolsalak@minsel.com',
      businessName: 'Dodol Salak Pinasungkulan',
      yearFounded: 2021,
      regency: 'Kab. Minahasa Selatan',
      district: 'Modoinding',
      village: 'Pinasungkulan',
      address: 'Jl. Wisata Danau Modoinding No. 14',
      postalCode: '95354',
      latitude: 0.8900,
      longitude: 124.4800,
      category: 'Makanan & Minuman',
      scale: 'Mikro',
      employeeCount: 4,
      mainProduct: 'Dodol & Olahan Salak',
      productType: 'Dodol Salak Manis Legit & Selai Salak',
      rawMaterial: 'Buah Salak Segar Modoinding',
      productionCapacity: '400 kotak / bulan',
      productPrice: 25000,
      productAdvantage: 'Manis asam segar alami buah salak, tanpa pewarna sintetik',
      nib: '9120007819204',
      businessLicense: 'Ada',
      npwp: null,
      halalCert: null,
      bpomPirt: 'P-IRT 2147105010291-26',
      haki: null,
      productionEquipment: 'Mixer Pengaduk Dodol Semi Otomatis',
      monthlyRevenue: 11000000,
      marketChannels: 'Offline',
      socialMedia: null,
      fundingSource: 'Modal Mandiri',
      bankAccess: 'Belum Ada',
      partnerships: 'Toko Buah Modoinding',
      needs: 'Fasilitasi Sertifikasi Halal & perbaikan daya simpan produk',
      ikmScore: 'Pemula',
      mentoringStatus: 'Pendampingan',
      status: 'APPROVED',
      adminNotes: 'Pemanfaatan panen buah salak lokal yang inovatif. Perlu fasilitasi label halal.',
      verifiedAt: new Date(),
      verifiedBy: 'Petugas Pembina IKM Sulut',
      ktpImage: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=600&auto=format&fit=crop&q=60',
      businessImage: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&auto=format&fit=crop&q=60',
    },
    {
      registrationNo: 'IKM-SULUT-2026-016',
      nik: '7110011506840002',
      ownerName: 'Rahmat Mamonto',
      phone: '081355667788',
      email: 'brikettutuyan@gmail.com',
      businessName: 'Briket Arang Batok Tutuyan',
      yearFounded: 2018,
      regency: 'Kab. Bolaang Mongondow Timur',
      district: 'Tutuyan',
      village: 'Tutuyan III',
      address: 'Jl. Trans Sulawesi Lingkar Selatan, Tutuyan',
      postalCode: '95771',
      latitude: 0.7780,
      longitude: 124.6200,
      category: 'Kimia & Bahan Bangunan',
      scale: 'Menengah',
      employeeCount: 12,
      mainProduct: 'Briket Arang Ekspor',
      productType: 'Briket Arang Batok Kelapa Shisha & Barbeque',
      rawMaterial: 'Tempurung Kelapa Tua Boltim',
      productionCapacity: '15 ton / bulan',
      productPrice: 18000,
      productAdvantage: 'Abu putih < 2.5%, kalori tinggi 7.200 kcal, minim asap',
      nib: '9120003319284',
      businessLicense: 'Ada',
      npwp: '76.812.991.4-824.000',
      halalCert: null,
      bpomPirt: null,
      haki: 'Tutuyan Charcoal Eco',
      productionEquipment: 'Mesin Ekstruder Briket, Oven Pengering Gas Skala 5 Ton',
      monthlyRevenue: 85000000,
      marketChannels: 'Offline',
      socialMedia: null,
      fundingSource: 'Modal Mandiri & Investor Lokal',
      bankAccess: 'Bank Mandiri Kredit Usaha',
      partnerships: 'Buyer Ekspor Timur Tengah via Surabaya',
      needs: 'Fasilitasi kontainer langsung dari Pelabuhan Bitung',
      ikmScore: 'Maju',
      mentoringStatus: 'Akses Pasar',
      status: 'APPROVED',
      adminNotes: 'Industri pengolahan limbah kelapa bernilai tambah tinggi dengan potensi devisa.',
      verifiedAt: new Date(),
      verifiedBy: 'Drs. Hendrik R. Tendean',
      ktpImage: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=600&auto=format&fit=crop&q=60',
      businessImage: 'https://images.unsplash.com/photo-1541888946425-d0fbb186c5f7?w=600&auto=format&fit=crop&q=60',
    },
    {
      registrationNo: 'IKM-SULUT-2026-017',
      nik: '7174015409860003',
      ownerName: 'Farida Mokodompit',
      phone: '081299881122',
      email: 'jahemerahkotamobagu@gmail.com',
      businessName: 'Minuman Herbal Jahe Merah',
      yearFounded: 2019,
      regency: 'Kota Kotamobagu',
      district: 'Kotamobagu Barat',
      village: 'Mogolaing',
      address: 'Jl. Kartini No. 42, Mogolaing',
      postalCode: '95716',
      latitude: 0.7350,
      longitude: 124.3180,
      category: 'Makanan & Minuman',
      scale: 'Kecil',
      employeeCount: 5,
      mainProduct: 'Serbuk Jahe Instan',
      productType: 'Minuman Serbuk Jahe Merah Plus Gula Aren',
      rawMaterial: 'Rimpang Jahe Merah Pegunungan Kotamobagu',
      productionCapacity: '1.200 pouch / bulan',
      productPrice: 30000,
      productAdvantage: 'Hangat menyegarkan, tanpa ampas, berkhasiat jaga daya tahan tubuh',
      nib: '9120007728190',
      businessLicense: 'Ada',
      npwp: '84.112.981.4-824.000',
      halalCert: 'ID7111000023412',
      bpomPirt: 'BPOM RI MD 269031002011',
      haki: 'Jahe Merah Totabuan',
      productionEquipment: 'Mesin Ekstraksi Sari Jahe, Pengkristal Otomatis',
      monthlyRevenue: 29000000,
      marketChannels: 'Online & Offline',
      socialMedia: '@jahemerah_totabuan',
      fundingSource: 'Modal Mandiri',
      bankAccess: 'Bank BSI KUR Mikro',
      partnerships: 'Apotek & Toko Herbal Se-Sulut',
      needs: 'Perluasan pasar online dan pameran herbal nasional',
      ikmScore: 'Berkembang',
      mentoringStatus: 'Sertifikasi',
      status: 'APPROVED',
      adminNotes: 'Izin BPOM MD sudah lengkap. Siap masuk jejaring apotek dan minimarket modern.',
      verifiedAt: new Date(),
      verifiedBy: 'Petugas Pembina IKM Sulut',
      ktpImage: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=600&auto=format&fit=crop&q=60',
      businessImage: 'https://images.unsplash.com/photo-1514733670139-4d87a1941d55?w=600&auto=format&fit=crop&q=60',
    },
    {
      registrationNo: 'IKM-SULUT-2026-018',
      nik: '7173021908810002',
      ownerName: 'Petrus Polii',
      phone: '081340776655',
      email: 'bambukinilow@gmail.com',
      businessName: 'Anyaman Bambu Kinilow',
      yearFounded: 2018,
      regency: 'Kota Tomohon',
      district: 'Tomohon Utara',
      village: 'Kinilow',
      address: 'Jl. Raya Manado - Tomohon Km 18, Kinilow',
      postalCode: '95439',
      latitude: 1.3520,
      longitude: 124.8310,
      category: 'Kerajinan',
      scale: 'Mikro',
      employeeCount: 4,
      mainProduct: 'Perlengkapan Rumah Anyaman',
      productType: 'Keranjang Bambu, Kap Lampu Estetik, Nampan Anyam',
      rawMaterial: 'Bambu Tali Hutan Kaki Gunung Lokon',
      productionCapacity: '250 unit / bulan',
      productPrice: 45000,
      productAdvantage: 'Anti rayap, anyaman halus bernuansa kearifan lokal Minahasa',
      nib: '9120005591024',
      businessLicense: 'Ada',
      npwp: null,
      halalCert: null,
      bpomPirt: null,
      haki: null,
      productionEquipment: 'Pisau Serut Bambu Baja, Cetakan Rangka Kayu',
      monthlyRevenue: 13500000,
      marketChannels: 'Offline',
      socialMedia: null,
      fundingSource: 'Modal Mandiri',
      bankAccess: 'Belum Ada',
      partnerships: 'Kafe & Resto Nuansa Alam Tomohon',
      needs: 'Pelatihan desain produk modern interior & etalase online',
      ikmScore: 'Pemula',
      mentoringStatus: 'Pendataan',
      status: 'APPROVED',
      adminNotes: 'Kerajinan tangan otentik Tomohon. Membutuhkan pendampingan desain modern.',
      verifiedAt: new Date(),
      verifiedBy: 'Petugas Pembina IKM Sulut',
      ktpImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&auto=format&fit=crop&q=60',
      businessImage: 'https://images.unsplash.com/photo-1590402494682-cd3fb53b1f70?w=600&auto=format&fit=crop&q=60',
    },
    {
      registrationNo: 'IKM-SULUT-2026-019',
      nik: '7106015509930004',
      ownerName: 'Clara Pangemanan',
      phone: '081143889900',
      email: 'sabun.sawangan@gmail.com',
      businessName: 'Sabun Herbal Kelapa Sawangan',
      yearFounded: 2021,
      regency: 'Kab. Minahasa Utara',
      district: 'Airmadidi',
      village: 'Sawangan',
      address: 'Kawasan Wisata Waruga Sawangan, Airmadidi',
      postalCode: '95371',
      latitude: 1.4150,
      longitude: 124.9520,
      category: 'Olahan Kelapa',
      scale: 'Kecil',
      employeeCount: 5,
      mainProduct: 'Sabun Organik VCO',
      productType: 'Sabun Batang Alami VCO & Ekstrak Daun Kelor',
      rawMaterial: 'Minyak Kelapa Murni, Ekstrak Herbal Alami',
      productionCapacity: '1.800 bar / bulan',
      productPrice: 28000,
      productAdvantage: 'Bebas SLS/Paraben, melembabkan kulit tropis, ramah lingkungan',
      nib: '9120008819203',
      businessLicense: 'Ada',
      npwp: '89.213.992.1-821.000',
      halalCert: 'Dalam Proses',
      bpomPirt: 'BPOM RI NA 18210500214',
      haki: 'Sawangan Pure Nature',
      productionEquipment: 'Mixer Homogenizer Stainless, Pemotong Sabun Presisi',
      monthlyRevenue: 36000000,
      marketChannels: 'Online',
      socialMedia: '@sawangannature (Instagram, Shopee Mall)',
      fundingSource: 'Modal Mandiri',
      bankAccess: 'Kredit BNI',
      partnerships: 'Spa & Hotel Berbintang Manado',
      needs: 'Fasilitasi Sertifikasi Halal Kosmetik & pameran ekspor kosmetik',
      ikmScore: 'Maju',
      mentoringStatus: 'Pendampingan',
      status: 'APPROVED',
      adminNotes: 'Izin BPOM NA kosmetik telah terbit. Memiliki prospek ekspor ke pasar Asia.',
      verifiedAt: new Date(),
      verifiedBy: 'Drs. Hendrik R. Tendean',
      ktpImage: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=600&auto=format&fit=crop&q=60',
      businessImage: 'https://images.unsplash.com/photo-1607006314144-88484f7b2f0c?w=600&auto=format&fit=crop&q=60',
    },
    {
      registrationNo: 'IKM-SULUT-2026-020',
      nik: '7103026207860002',
      ownerName: 'Marlina Makausi',
      phone: '085244119933',
      email: 'bageasangihe@gmail.com',
      businessName: 'Kue Bagea Sangihe',
      yearFounded: 2019,
      regency: 'Kab. Kepulauan Sangihe',
      district: 'Manganitu',
      village: 'Barangka',
      address: 'Jl. Trans Manganitu No. 15',
      postalCode: '95852',
      latitude: 3.5500,
      longitude: 125.5200,
      category: 'Makanan & Minuman',
      scale: 'Mikro',
      employeeCount: 3,
      mainProduct: 'Kue Tradisional Sagu Bagea',
      productType: 'Bagea Kenari & Bagea Jahe Kayu Manis',
      rawMaterial: 'Tepung Sagu Barangka, Kacang Kenari, Gula Aren',
      productionCapacity: '500 kaleng / bulan',
      productPrice: 28000,
      productAdvantage: 'Bebas gluten (Gluten Free), renyah gurih manis pas',
      nib: '9120003391024',
      businessLicense: 'Ada',
      npwp: null,
      halalCert: null,
      bpomPirt: 'P-IRT 2067103010321-25',
      haki: null,
      productionEquipment: 'Oven Roti Gas Stainless, Mixer Adonan Sagu',
      monthlyRevenue: 13000000,
      marketChannels: 'Offline',
      socialMedia: null,
      fundingSource: 'Modal Mandiri',
      bankAccess: 'Belum Ada',
      partnerships: 'Toko Oleh-oleh Tahuna & Pelabuhan',
      needs: 'Fasilitasi Sertifikasi Halal dan kemasan kaleng printing modern',
      ikmScore: 'Pemula',
      mentoringStatus: 'Pendampingan',
      status: 'APPROVED',
      adminNotes: 'Kuliner warisan Sangihe berbasis sagu lokal. Memerlukan bantuan desain kemasan.',
      verifiedAt: new Date(),
      verifiedBy: 'Petugas Pembina IKM Sulut',
      ktpImage: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=600&auto=format&fit=crop&q=60',
      businessImage: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=600&auto=format&fit=crop&q=60',
    },
    {
      registrationNo: 'IKM-SULUT-2026-021',
      nik: '7171021408870003',
      ownerName: 'Ronald Wowor',
      phone: '081288334455',
      email: 'sambalroa.judes@gmail.com',
      businessName: 'Sambal Roa Judes Manado',
      yearFounded: 2017,
      regency: 'Kota Manado',
      district: 'Sario',
      village: 'Sario Tumpaan',
      address: 'Jl. Sam Ratulangi No. 204, Sario',
      postalCode: '95114',
      latitude: 1.4680,
      longitude: 124.8320,
      category: 'Makanan & Minuman',
      scale: 'Kecil',
      employeeCount: 9,
      mainProduct: 'Sambal Ikan Roa Asap',
      productType: 'Sambal Roa Kering & Sambal Roa Basah Minyak Kelapa',
      rawMaterial: 'Ikan Roa Asap Pulau Tagulandang Pilihan',
      productionCapacity: '3.500 botol / bulan',
      productPrice: 42000,
      productAdvantage: 'Ikan roa terasa gurih melimpah, tidak amis, tahan 12 bulan',
      nib: '9120004481923',
      businessLicense: 'Ada',
      npwp: '78.912.441.2-821.000',
      halalCert: 'ID7111000004512',
      bpomPirt: 'P-IRT 2117171010452-25',
      haki: 'Sambal Roa Judes',
      productionEquipment: 'Mesin Penumbuk Ikan Roa, Sealer Induksi Aluminium Foil',
      monthlyRevenue: 75000000,
      marketChannels: 'Online & Offline',
      socialMedia: '@sambalroajudes (Instagram, Shopee, Tokopedia)',
      fundingSource: 'Modal Mandiri & KUR BRI',
      bankAccess: 'Kredit Usaha Rakyat BRI',
      partnerships: 'Bandara Sam Ratulangi, Restoran Garuda',
      needs: 'Business matching eksportir diaspora Indonesia di Amerika & Australia',
      ikmScore: 'Maju',
      mentoringStatus: 'Akses Pasar',
      status: 'APPROVED',
      adminNotes: 'Ikonik oleh-oleh Manado. Masuk daftar unggulan promosi luar negeri.',
      verifiedAt: new Date(),
      verifiedBy: 'Drs. Hendrik R. Tendean',
      ktpImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&auto=format&fit=crop&q=60',
      businessImage: 'https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?w=600&auto=format&fit=crop&q=60',
    },
    {
      registrationNo: 'IKM-SULUT-2026-022',
      nik: '7108011204850001',
      ownerName: 'Ismail Van Gobel',
      phone: '085255443322',
      email: 'minyak.boroko@gmail.com',
      businessName: 'Minyak Kelapa Kampung Boroko',
      yearFounded: 2020,
      regency: 'Kab. Bolaang Mongondow Utara',
      district: 'Kaidipang',
      village: 'Boroko',
      address: 'Desa Boroko Timur, Kaidipang',
      postalCode: '95765',
      latitude: 0.8850,
      longitude: 123.9520,
      category: 'Olahan Kelapa',
      scale: 'Mikro',
      employeeCount: 4,
      mainProduct: 'Minyak Goreng Kelapa Murni',
      productType: 'Minyak Kelapa Tanpa Bahan Kimia',
      rawMaterial: 'Kelapa Kebun Rakyat Pesisir Bolmut',
      productionCapacity: '1.200 liter / bulan',
      productPrice: 28000,
      productAdvantage: 'Bening alami, aroma harum gurih menggugah selera',
      nib: '9120001928471',
      businessLicense: 'Ada',
      npwp: null,
      halalCert: 'Dalam Proses',
      bpomPirt: 'P-IRT 2057108010192-26',
      haki: null,
      productionEquipment: 'Mesin Parut Kelapa & Pemeras Santan Stainless',
      monthlyRevenue: 22000000,
      marketChannels: 'Offline',
      socialMedia: null,
      fundingSource: 'Modal Mandiri',
      bankAccess: 'Belum Ada',
      partnerships: 'Pasar Tradisional Boroko & Gorontalo',
      needs: 'Pendampingan pemasaran digital & fasilitasi kemasan botol higienis',
      ikmScore: 'Berkembang',
      mentoringStatus: 'Analisis Kebutuhan',
      status: 'APPROVED',
      adminNotes: 'Kualitas minyak kelapa sangat murni. Perluasan pasar ke ibukota Manado.',
      verifiedAt: new Date(),
      verifiedBy: 'Petugas Pembina IKM Sulut',
      ktpImage: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=600&auto=format&fit=crop&q=60',
      businessImage: 'https://images.unsplash.com/photo-1620706857370-e1b9770e8bb1?w=600&auto=format&fit=crop&q=60',
    },
    {
      registrationNo: 'IKM-SULUT-2026-023',
      nik: '7111011802900003',
      ownerName: 'Yahya Mooduto',
      phone: '081399445566',
      email: 'ikanasin.molibagu@gmail.com',
      businessName: 'Pengeringan Ikan Asin Molibagu',
      yearFounded: 2022,
      regency: 'Kab. Bolaang Mongondow Selatan',
      district: 'Bolaang Uki',
      village: 'Molibagu',
      address: 'Pesisir Pantai Molibagu, Bolaang Uki',
      postalCode: '95774',
      latitude: 0.3850,
      longitude: 123.9550,
      category: 'Perikanan',
      scale: 'Mikro',
      employeeCount: 3,
      mainProduct: 'Ikan Teri & Asin Kering',
      productType: 'Ikan Teri Nasi Kering & Ikan Belanak Asin',
      rawMaterial: 'Hasil Tangkapan Nelayan Teluk Tomini',
      productionCapacity: '600 kg / bulan',
      productPrice: 45000,
      productAdvantage: 'Kadar garam seimbang, penjemuran higienis jaring kasa',
      nib: null,
      businessLicense: 'Belum Ada',
      npwp: null,
      halalCert: null,
      bpomPirt: null,
      haki: null,
      productionEquipment: 'Para-para Jemur Jaring Kasa Higienis',
      monthlyRevenue: 12500000,
      marketChannels: 'Offline',
      socialMedia: null,
      fundingSource: 'Modal Mandiri',
      bankAccess: 'Belum Ada',
      partnerships: 'Pedagang Ikan Kering Pasar Kotamobagu',
      needs: 'Fasilitasi pembuatan NIB gratis dan alat pengemas vacuum',
      ikmScore: 'Pemula',
      mentoringStatus: 'Pendataan',
      status: 'PENDING',
      adminNotes: 'Data belum lengkap (NIB & izin edar belum ada). Menunggu pendampingan registrasi NIB.',
      verifiedAt: null,
      verifiedBy: null,
      ktpImage: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=600&auto=format&fit=crop&q=60',
      businessImage: 'https://images.unsplash.com/photo-1534939561126-855b8675edd7?w=600&auto=format&fit=crop&q=60',
    },
    {
      registrationNo: 'IKM-SULUT-2026-024',
      nik: '7109025501830002',
      ownerName: 'Grace Salindeho',
      phone: '081244990033',
      email: 'siruppala.sitaro@gmail.com',
      businessName: 'Sirup Pala Tagulandang',
      yearFounded: 2018,
      regency: 'Kab. Kepulauan Sitaro',
      district: 'Tagulandang',
      village: 'Balehumara',
      address: 'Jl. Bahari No. 9, Tagulandang',
      postalCode: '95863',
      latitude: 2.3380,
      longitude: 125.4120,
      category: 'Makanan & Minuman',
      scale: 'Kecil',
      employeeCount: 6,
      mainProduct: 'Sirup & Manisan Buah Pala',
      productType: 'Sirup Buah Pala Murni & Manisan Pala Basah/Kering',
      rawMaterial: 'Daging Buah Pala Matang Pohon Tagulandang',
      productionCapacity: '1.000 botol / bulan',
      productPrice: 35000,
      productAdvantage: 'Kaya antioksidan, rasa segar hangat menghangatkan tenggorokan',
      nib: '9120008829104',
      businessLicense: 'Ada',
      npwp: '79.112.441.2-823.000',
      halalCert: 'ID7111000091823',
      bpomPirt: 'P-IRT 2147109010192-25',
      haki: 'Pala Tagulandang Segar',
      productionEquipment: 'Mesin Press Buah Pala, Sterilisator Botol Kaca',
      monthlyRevenue: 31000000,
      marketChannels: 'Online & Offline',
      socialMedia: '@siruppala_sitaro (Instagram)',
      fundingSource: 'Modal Mandiri',
      bankAccess: 'Bank SulutGo KUR',
      partnerships: 'Hotel dan Pusat Oleh-oleh Manado',
      needs: 'Fasilitasi pameran minuman Nusantara & desain label kemasan premium',
      ikmScore: 'Berkembang',
      mentoringStatus: 'Sertifikasi',
      status: 'APPROVED',
      adminNotes: 'Pemanfaatan daging buah pala kepulauan yang bernilai tinggi.',
      verifiedAt: new Date(),
      verifiedBy: 'Petugas Pembina IKM Sulut',
      ktpImage: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=600&auto=format&fit=crop&q=60',
      businessImage: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=600&auto=format&fit=crop&q=60',
    },
    {
      registrationNo: 'IKM-SULUT-2026-025',
      nik: '7104031904870001',
      ownerName: 'Yulius Bawias',
      phone: '082199443311',
      email: 'kerajinankerang.talaud@gmail.com',
      businessName: 'Kerajinan Kerang Melonguane',
      yearFounded: 2022,
      regency: 'Kab. Kepulauan Talaud',
      district: 'Melonguane Timur',
      village: 'Sawang',
      address: 'Pesisir Pantai Sawang, Melonguane',
      postalCode: '95885',
      latitude: 4.0200,
      longitude: 126.7100,
      category: 'Kerajinan',
      scale: 'Mikro',
      employeeCount: 3,
      mainProduct: 'Hiasan & Aksesoris Kerang',
      productType: 'Lampu Meja Kerang Mutiara, Kotak Tisu, Kalung Etnik',
      rawMaterial: 'Cangkang Kerang Laut Mati Terdampar Pantai',
      productionCapacity: '150 pcs / bulan',
      productPrice: 50000,
      productAdvantage: 'Kerajinan unik kepulauan terluar, kilau alami kerang mutiara',
      nib: null,
      businessLicense: 'Dalam Proses',
      npwp: null,
      halalCert: null,
      bpomPirt: null,
      haki: null,
      productionEquipment: 'Alat Poles Kerang Gerinda Mini, Lem Resin UV',
      monthlyRevenue: 9500000,
      marketChannels: 'Offline',
      socialMedia: null,
      fundingSource: 'Modal Mandiri',
      bankAccess: 'Belum Ada',
      partnerships: 'Dinas Pariwisata Kab. Talaud',
      needs: 'Fasilitasi penerbitan NIB & bantuan mesin poles kerang elektrik',
      ikmScore: 'Pemula',
      mentoringStatus: 'Analisis Kebutuhan',
      status: 'PENDING',
      adminNotes: 'Data legalitas belum lengkap. Dijadwalkan untuk pendampingan penerbitan NIB mandiri.',
      verifiedAt: null,
      verifiedBy: null,
      ktpImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&auto=format&fit=crop&q=60',
      businessImage: 'https://images.unsplash.com/photo-1538688525198-9b88f6f53126?w=600&auto=format&fit=crop&q=60',
    }
  ];

  for (const ikm of pilotIKM) {
    await prisma.merchantRegistration.create({
      data: ikm,
    });
  }

  console.log(`Successfully seeded ${pilotIKM.length} authentic Pilot Project IKM Sulawesi Utara!`);
}

main()
  .catch((e) => {
    console.error('Error seeding data:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
